services:
  buckaroo.config.api.fee.service:
    class: Buckaroo\PrestaShop\Src\Service\BuckarooFeeService
    arguments:
      - "@doctrine.orm.entity_manager"
    public: true
  buckaroo.config.api.config.service:
    class:  Buckaroo\PrestaShop\Src\Service\BuckarooConfigService
    arguments:
      - "@doctrine.orm.entity_manager"
    public: true
  buckaroo.classes.issuers.capayableIn3:
    class: Buckaroo\PrestaShop\Classes\CapayableIn3
    arguments:
      - "@buckaroo.config.api.config.service"
    public: true
  buckaroo.classes.issuers.payByBank:
    class: Buckaroo\PrestaShop\Classes\IssuersPayByBank
    public: true
  buckaroo.repository.country.repository:
    class: Buckaroo\PrestaShop\Src\Repository\CountryRepository
    public: true
  buckaroo.config.api.payment.service:
    class: Buckaroo\PrestaShop\Src\Service\BuckarooPaymentService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@buckaroo.config.api.fee.service"
      - "@buckaroo.config.api.config.service"
      - "@buckaroo.classes.issuers.payByBank"
      - "@buckaroo.classes.issuers.capayableIn3"
      - "@buckaroo.repository.country.repository"
    public: true
