<?php
namespace Buckaroo\Prestashop\Config;

use Configuration;
class Config
{
    const BUCKAROO_TEST = 'BUCKAROO_TEST';
    const BUCKAROO_MERCHANT_KEY = 'BUCKAROO_MERCHANT_KEY';
    const BUCKAROO_SECRET_KEY = 'BUCKAROO_SECRET_KEY';
    const BUCKAROO_TRANSACTION_LABEL = 'BUCKAROO_TRANSACTION_LABEL';
    const BUCKAROO_TRANSACTION_FEE = 'BUCKAROO_TRANSACTION_FEE';
    const BUCKAROO_IDEAL_MODE = 'BUCKAROO_IDEAL_MODE';
    const BUCKAROO_IDEAL_LABEL = 'BUCKAROO_IDEAL_LABEL';
    const BUCKAROO_IDEAL_FEE = 'BUCKAROO_IDEAL_FEE';
    const BUCKAROO_IDEAL_MIN_VALUE = 'BUCKAROO_IDEAL_MIN_VALUE';
    const BUCKAROO_IDEAL_MAX_VALUE = 'BUCKAROO_IDEAL_MAX_VALUE';
    const BUCKAROO_IDEAL_DISPLAY_TYPE = 'BUCKAROO_IDEAL_DISPLAY_TYPE';
    const BUCKAROO_PAYBYBANK_MODE = 'BUCKAROO_PAYBYBANK_MODE';
    const BUCKAROO_PAYBYBANK_LABEL = 'BUCKAROO_PAYBYBANK_LABEL';
    const BUCKAROO_PAYBYBANK_MIN_VALUE = 'BUCKAROO_PAYBYBANK_MIN_VALUE';
    const BUCKAROO_PAYBYBANK_MAX_VALUE = 'BUCKAROO_PAYBYBANK_MAX_VALUE';
    const BUCKAROO_PAYBYBANK_DISPLAY_TYPE = 'BUCKAROO_PAYBYBANK_DISPLAY_TYPE';
    const BUCKAROO_PAYPAL_MODE = 'BUCKAROO_PAYPAL_MODE';
    const BUCKAROO_PAYPAL_SELLER_PROTECTION_ENABLED = 'BUCKAROO_PAYPAL_SELLER_PROTECTION_ENABLED';
    const BUCKAROO_PAYPAL_LABEL = 'BUCKAROO_PAYPAL_LABEL';
    const BUCKAROO_PAYPAL_FEE = 'BUCKAROO_PAYPAL_FEE';
    const BUCKAROO_PAYPAL_MIN_VALUE = 'BUCKAROO_PAYPAL_MIN_VALUE';
    const BUCKAROO_PAYPAL_MAX_VALUE = 'BUCKAROO_PAYPAL_MAX_VALUE';
}
