buckaroo_refund:
    path: buckaroo3/refund
    methods: [POST]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\AdminRefundController::refund'

buckaroo_config_paymentMethod:
    path: buckaroo3/config/payment/methods
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\PaymentMethodConfig::initContent'
    options:
        expose: true

buckaroo_config_countries:
    path: buckaroo3/config/countries
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\Countries::initContent'
    options:
        expose: true

buckaroo_config_creditcards:
    path: buckaroo3/config/creditcards
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\Creditcards::initContent'
    options:
        expose: true

buckaroo_config_orderings:
    path: buckaroo3/config/orderings
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\Orderings::initContent'
    options:
        expose: true

buckaroo_config_methodMode:
    path: buckaroo3/config/methodMode
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\PaymentMethodMode::initContent'
    options:
        expose: true

buckaroo_config_methods:
    path: buckaroo3/config/methods
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\PaymentMethods::initContent'
    options:
        expose: true

buckaroo_config_settings:
    path: buckaroo3/config/settings
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\Settings::initContent'
    options:
        expose: true

buckaroo_config_testCredentials:
    path: buckaroo3/config/testCredentials
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\TestCredentialsApi::initContent'
    options:
        expose: true

buckaroo_config_verificationMethods:
    path: buckaroo3/config/verificationMethods
    methods: [POST, GET]
    defaults:
        _controller: 'Buckaroo\PrestaShop\Controllers\admin\VerificationMethods::initContent'
    options:
        expose: true