name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist

      - name: Run tests
        run: |
          ./vendor/bin/phpunit --configuration tests/phpunit.xml